name: Build Corretto 21 GenShen for Windows
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Disable git autocrlf
        run: git config --global core.autocrlf false

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'generational-shenandoah'
          
      - name: Setup Boot JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Install Cygwin (Required for build)
        uses: egor-tensin/setup-cygwin@v4
        with:
          platform: x64
          packages: autoconf make zip unzip git

      - name: Configure and Build
        shell: bash
        # 【关键修复】使用单行执行，避免行尾的 \r 被吃进参数里
        run: bash configure --with-toolchain-version=2022 && make images

      - name: Upload JDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-jdk-21-genshen
          path: build/windows-x86_64-server-release/images/jdk
